### PR TITLE
Add ruby-builder image based on Debian Stretch

### PR DESCRIPTION
**Pull request by mthssdrbrg**
What it says on the tin.

### CODE REVIEW

**Review by sata — APPROVED** [review]
One question, how do I figure out what version is available when we have merged this and built a new one? I'm using `quay.io/pusher/ruby-builder:v20200130-827c4f3-dirty` at the moment

**Comment by sata** [comment]
Thanks for all the help @mthssdrbrg

**Review by theobarberbany — APPROVED** [review]

**Pull request merged**
