### PR TITLE
Add Snyk CLI to builder and set up scanning for Faros

### PR DESCRIPTION
**Pull request by JoelSpeed**
Adds the Snyk CLI binary to all builder images and adds a preset to allow jobs to authenticate to Snyk and send reports

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Need to replace the secret on this PR with the pusher-ci bot token

**Comment by JoelSpeed** [comment]
This now uses an API token for the @pusher-ci Snyk account

**Review by wonderhoss — APPROVED** [review]
LGTM

**Pull request merged**
