### PR TITLE
Add more linting tools to golang-builder

### PR DESCRIPTION
**Pull request by JoelSpeed**
This adds a bunch more tools and linters to the golang-builder image that I have seen being used in our projects.

Also updates golangci-lint to 1.17.1

### CODE REVIEW

**Comment by BenPope** [comment]
Golangci-lint 1.17.1 fails on some of our repos. Can we choose to swap this out for a different version, or choose the version of the base image? This is likely to be a problem in the future - any updates to the base image could prevent existing successful repos from building. This is a tricky trade-off between keeping things up to date automagically and breaking previously working stuff.

What would be required to use, say: https://github.com/pusher/elements-alpine-golang-build as a build base?

**Review by wonderhoss — DISMISSED** [review]

**Comment by JoelSpeed** [comment]
> Can we choose to swap this out for a different version

Happy to leave this on an older version for now, was just updating it to match `elements-alpine-golang-build`

> or choose the version of the base image?

It is possible to pin the base images if you wish to, just add a comment in the PreSubmit after the image tag explaining why it is pinned and it will be kept at that version

> https://github.com/pusher/elements-alpine-golang-build as a build base?

You _could_ use this image, though since it doesn't have our entrypoint runner script, it won't work quite the same and a number of the Presets won't work with it (eg docker-in-docker)

**Comment by BenPope** [comment]
> Happy to leave this on an older version for now, was just updating it to match `elements-alpine-golang-build`

Yeah - I recently updated it, but haven't moved over any repos due to the linting failing.  When we get round to fixing that, we can bump it up, maybe. 1.16.0 is what we're currently using.

**Comment by JoelSpeed** [comment]
Happy to leave it on 1.15.0 for now and update later once we have time to look into it, for now if we know this version works, let's keep it, happy for me to merge just the additional tools?

**Review by BenPope — APPROVED** [review]

**Pull request merged**
